/* generated loose typings for the JS engine */
export declare const PREQ: any
export declare const addBidder: any
export declare const addD: any
export declare const addDoc: any
export declare const addTask: any
export declare const advance: any
export declare const asc: any
export declare const clockNext: any
export declare const closeProc: any
export declare const commClose: any
export declare const createProc: any
export declare const csvExport: any
export declare const decideApproval: any
export declare const declineBid: any
export declare const docs: any
export declare const ensureState: any
export declare const evalBid: any
export declare const failProc: any
export declare const genMatrix: any
export declare const genSSD: any
export declare const matrixHTML: any
export declare const num: any
export declare const openBids: any
export declare const openingHTML: any
export declare const procLabel: any
export declare const recvBid: any
export declare const removeBidder: any
export declare const requestApproval: any
export declare const resetDemo: any
export declare const resolveSingle: any
export declare const sample: any
export declare const save: any
export declare const saveNego: any
export declare const savePrequal: any
export declare const saveTco: any
export declare const sendTender: any
export declare const setCtype: any
export declare const setFlag: any
export declare const setInput: any
export declare const ssdHTML: any
export declare const tcoCalc: any
export declare const toggleTask: any
export declare const uploadDoc: any
