/* generated loose typings for the JS engine */
export declare const ADESC: any
export declare const ATITLE: any
export declare const BOUND: any
export declare const CC: any
export declare const CEO: any
export declare const DOCS: any
export declare const FOLDERS: any
export declare const INF: any
export declare const MON: any
export declare const MONL: any
export declare const ORGS: any
export declare const P: any
export declare const S: any
export declare const SKEY: any
export declare const STAGES: any
export declare const TYPEDESC: any
export declare const USERS: any
export declare const W: any
export declare const WDN: any
export declare const addD: any
export declare const addWD: any
export declare const allResp: any
export declare const allTodos: any
export declare const apprState: any
export declare const auditHash: any
export declare const bidVisible: any
export declare const boundKey: any
export declare const ccApprover: any
export declare const checklist: any
export declare const commFilled: any
export declare const decide: any
export declare const diffD: any
export declare const dl: any
export declare const docLatest: any
export declare const docs: any
export declare const esc: any
export declare const fDay: any
export declare const fShort: any
export declare const fdt: any
export declare const ft: any
export declare const h53: any
export declare const iso: any
export declare const load: any
export declare const log: any
export declare const nextDue: any
export declare const nextId: any
export declare const nextItem: any
export declare const nextStage: any
export declare const nf: any
export declare const pd: any
export declare const pendingFor: any
export declare const ranking: any
export declare const rel: any
export declare const required: any
export declare const rules: any
export declare const save: any
export declare const seedState: any
export declare const setS: any
export declare const short: any
export declare const skipped: any
export declare const stamp: any
export declare const statusOf: any
export declare const tcoReq: any
export declare const techDone: any
export declare const techOk: any
export declare const typeOf: any
export declare const uid: any
export declare const validBids: any
export declare const verifyChain: any
export declare const CFO: any
export declare const SCM: any
export declare const MI: any
export declare const ADM: any
export declare const JOGI: any
export declare const PENZ: any
export declare const MDM: any
export declare const RAKT: any
